main:
  - name: "首页"
    pageRef: "/"
    weight: 10
  - name: "分类"
    weight: 20
  - name: "PostgreSQL案例"
    parent: "分类"
    pageRef: "categories/postgresql案例"
    weight: 1
  - name: "PostgreSQL内功修炼"
    parent: "分类"
    pageRef: "categories/postgresql内功修炼"
    weight: 2
  - name: "PostgreSQL源码解析"
    parent: "分类"
    pageRef: "categories/postgresql源码解析"
    weight: 3
  - name: "论文解读"
    parent: "分类"
    pageRef: "categories/论文解读"
    weight: 4
  - name: "读书笔记"
    parent: "分类"
    pageRef: "categories/读书笔记"
    weight: 5
  - name: "杂项"
    parent: "分类"
    pageRef: "categories/杂项"
    weight: 6
  - name: "AIOps"
    parent: "分类"
    pageRef: "categories/aiops"
    weight: 7
  - name: "关于"
    pageRef: "about"
    weight: 30
  - name: "x-twitter"
    url: "https://x.com/liuzhilong62"
    pre: "x-twitter"
    weight: 40
  - name: "github"
    url: "https://github.com/liuzhilong62"
    pre: "github"
    weight: 50
